constantine.nimble
constantine/arithmetic/finite_fields.nim
constantine/arithmetic/montgomery.nim
constantine/arithmetic/precomputed.nim
constantine/config/curves.nim
constantine/primitives/extended_precision.nim
constantine/primitives/extended_precision_64bit_uint128.nim
constantine/primitives/extended_precision_x86_64_msvc.nim
tests/test_finite_fields_mulsquare.nim
tests/test_finite_fields_mulsquare.nim.cfg
tests/test_finite_fields_powinv.nim

This implements a specialized path for squaring.
On i9-9980XE overclocked all-core turbo at 4.1GHz
Using Clang and -d:danger (GCC is significantly slower i.e. 188 cycles for field multiplication of BLS12_381 instead of 137 cycles.)
```
Warmup: 0.9125 s, result 224 (displayed to avoid compiler optimizing warmup away)
⚠️ Measurements are approximate and use the CPU nominal clock: Turbo-Boost and overclocking will skew them.
==========================================================================================================
Addition        Fp[Secp256k1]           2 ns         8 cycles
Substraction    Fp[Secp256k1]           2 ns         6 cycles
Negation        Fp[Secp256k1]           0 ns         0 cycles
Multiplication  Fp[Secp256k1]          22 ns        68 cycles
Squaring …
```

Add optimized squaring (~15% speedup)

---

constantine.nimble
constantine/arithmetic/bigints.nim
constantine/arithmetic/finite_fields.nim
constantine/arithmetic/precomputed.nim
constantine/config/curves.nim
tests/test_finite_fields_mulsquare.nim
tests/test_finite_fields_sqrt.nim
tests/test_finite_fields_sqrt.nim.cfg

This adds modular square root computation for moduli p ≡ 3 (mod 4).
This covers most curves:
- BN254
- P256
- Secp256k1
- BLS12_381
- BN446
- FKM12_447
- BLS12_461
- BN462
Modular square root is useful to create a point on an elliptic curve by setting the `x` coordinates and inferring the `y` coordinate from the curve equation: `y² = x³ + ax + b`.
This will allow testing the https://github.com/mratsim/constantine/tree/elliptic-curve branch.
_Note: you can also get a random point on the curve by multiplying a generator point with a random scalar but that requires having scalar multiplication (and so point addition and doubling) correctly implemented, so we would still need a way to test that they are properly implemented._

Square roots

---

constantine/arithmetic/finite_fields_inversion.nim
constantine/arithmetic/limbs_modular.nim
constantine/arithmetic/precomputed.nim
constantine/config/curves.nim
constantine/config/curves_parser.nim
tests/test_finite_fields_powinv.nim
tests/test_finite_fields_sqrt.nim

This:
- Adds a new `CurveFamily` enum. For now only used for Barreto-Naehrig family and in the future to specialize pairing per curve family
- Adds a specialized inversion scheme that uses the low Hamming Weight and special form of BN primes if the base BN parameter is positive like for the SNARKS / Ethereum alt_bn128 curve. Unfortunately this is actually significantly slower than the current generic inversion and so is not activated. Furthermore some inputs are failing and need to be debugged. The test suite has been expanded to catch those cases.

Improve bn curve family support

---

constantine/arithmetic/limbs_modular.nim

This replace memcpy/memmove (copyMem and moveMem in Nim speak).
I suspect the Windows 32-bit image used by Github CI doesn't properly implement memmove #56
This also is required anyway to be able to do reductions at compile-time.

Don't use memcpy / memmove

---

helpers/prng_unsafe.nim
tests/t_ec_template.nim
tests/t_finite_fields_mulsquare.nim
tests/t_finite_fields_powinv.nim
tests/t_finite_fields_sqrt.nim
tests/t_fp_tower_template.nim

This PR addresses #53.
- An uniform RNG has a hard time triggering carry paths, especially with 64-bit word, the probability is 2^-64 * 2^-64 = 2^-128.
- A significant amount of algebra bugs in established libraries like OpenSSL are due to carries. ![algebra bugs](https://user-images.githubusercontent.com/22738317/85069647-c248c500-b1b4-11ea-8bd6-5c2900e3e8cc.png)
- Most fuzzing tools like AFL or LibFuzzer are branch coverage based, but constant-time code is branchless so it's likely that they won't focus on the carry path as it's indistinguishable from the normal path from a Control Flow Graph perspective.
and found [CVE-2014-3570](https://www.openssl.org/news/secadv/20150108.txt) in OpenSSL and would likely have found similar bug in TweetNaCK: …

[WIP] Skewed RNGs that trigger corner cases

---

constantine.nimble
constantine/arithmetic/finite_fields.nim
constantine/arithmetic/limbs_montgomery.nim
tests/t_ec_wstrass_prj_edge_cases.nim
tests/t_ec_wstrass_prj_g1_mul_sanity.nim
tests/t_finite_fields_mulsquare.nim
tests/t_finite_fields_powinv.nim
tests/t_finite_fields_sqrt.nim
tests/t_fp2_sqrt.nim
tests/t_primitives_extended_precision.nim

This PR
- Fix #30, #42, #43, #60, #61, #62, #64, #65, #67, (#65 has 3 cases.)
Reactivating the squaring which would reenable a significant 20% performance improvement is tracked in #68.
Note that the error is an off-by-one in the least significant bit in the Montgomery representation.
It happens in both the generic squaring algorithm and the fast squaring from Consensys.
I suspect a carry is missing from the literature, though the literature on Montgomery squaring is pretty scarce.

Fuzzing campaign fixes

---

constantine.nimble
constantine/arithmetic/finite_fields.nim
constantine/config/precompute.nim
constantine/elliptic/ec_scalar_mul.nim
constantine/io/io_towers.nim
constantine/isogeny/frobenius.nim
constantine/primitives/constant_time.nim
constantine/tower_field_extensions/quadratic_extensions.nim
sage/curve_family_bls12.sage
sage/curve_family_bn.sage
sage/frobenius_bls12_377.sage
sage/frobenius_bls12_381.sage
sage/frobenius_bn254_snarks.sage
tests/t_bigints.nim
tests/t_ec_frobenius.nim
tests/t_ec_sage_bn254.nim
tests/t_ec_template.nim

This PR adds:
- The Frobenius Endomorphism over Fp2 πp
- The Endomorphism ψ (psi): untwist-Frobenius-Twist from [Galbraith-Scott 2008](https://eprint.iacr.org/2008/117.pdf)
- An optimized ψ² to apply ψ twice
This is necessary for:
- Pairing implementation
- Accelerating scalar multiplication on G2 (likely 3x~4x) by endomorphism decomposition as only G1 is accelerated (#44) using [Faz-Hernandez Longa Sanchez 2013](https://eprint.iacr.org/2013/158.pdf)
- Fast clear cofactor method using for BN on G2 via [Fuentes Castaneda 2011](http://cacr.uwaterloo.ca/techreports/2011/cacr2011-26.pdf) and for BLS on G2 [Budroni-Pintore 2017](https://eprint.iacr.org/2017/419.pdf) and on G1 [Wahby-Boneh 2019, personal communication from Scott](https://eprint.iacr.org/2019/403.pdf)
- Fast subgroup checks on …

Frobenius endomorphism ψ = φ−1 πp φ (psi = untwist-Frobenius-Twist)

---

benchmarks/bench_pairing_bn254_nogami.nim
benchmarks/bench_pairing_bn254_snarks.nim
benchmarks/bench_pairing_template.nim
constantine.nimble
constantine/config/curves_declaration.nim
constantine/isogeny/frobenius.nim
constantine/pairing/README.md
constantine/pairing/cyclotomic_fp12.nim
constantine/pairing/mul_fp12_by_lines.nim
constantine/pairing/pairing_bls12.nim
constantine/pairing/pairing_bn.nim
sage/frobenius_bls12_381.sage
sage/frobenius_bn254_nogami.sage
sage/frobenius_bn254_snarks.sage
tests/t_fp12_frobenius.nim
tests/t_fp2_frobenius.nim
tests/t_fp4_frobenius.nim
tests/t_fp6_frobenius.nim
tests/t_pairing_bn254_nogami_optate.nim
tests/t_pairing_bn254_snarks_optate.nim
tests/t_pairing_mul_fp12_by_lines.nim

This implements pairings for:
- BN254-Nogami, BN curve with parameter -0x4080000000000001
- BN254-Snarks, BN curve with parameter 0x44e992b44a6909f1 for high 2-adicity (2^32) for BigInt FFT in Snarks applications
The BN254-Nogami has a decent 0.4 ms single pairing time
BN254-Snarks is at 0.64 ms

Pairings for BN254-Nogami and BN254-Snarks

---

constantine/primitives/macro_assembler_x86.nim

Not sure why I needed different codegen for GCC and CLang, it was actually unnecessary?
Or maybe the parenthesis changes everything compared to the original test code https://github.com/mratsim/finite-fields/blob/master/macro_add_carry.nim#L24-L42
```Nim
when defined(gcc):
for byteOffset in countup(wsize, maxByteOffset-1, wsize):
asmStmt.add (block:
"\n" &
"      movq " & $byteOffset & "+%[b], %[tmp]\n" &
"      adcq %[tmp], " & $byteOffset & "+%[a]\n"
)
elif defined(clang):
for byteOffset in countup(wsize, maxByteOffset-1, wsize):
asmStmt.add (block:
"\n" &
"      movq " & $byteOffset & "%[b], %[tmp]\n" &
"      adcq %[tmp], " & $byteOffset & "%[a]\n"
)
```

Unify GCC and Clang ASM

---

.github/workflows/ci.yml
.travis.yml
azure-pipelines.yml
benchmarks/bench_sha256.nim
constantine.nimble

Fix test suite

---

constantine/arithmetic/limbs.nim
constantine/curves/zoo_inversions.nim

Revert part of #95, fix #134
Before GCC compiler
Before Clang
After GCC
After Clang
Conclusion
Implement stuff in assembly ...

Fix 50% perf regression (2x with GCC) on binary GCD based inversion

---

constantine.nimble
constantine/arithmetic/assembly/limbs_asm_modular_x86.nim
constantine/arithmetic/assembly/limbs_asm_montred_x86_adx_bmi2.nim
constantine/arithmetic/bigints.nim
constantine/arithmetic/finite_fields.nim
constantine/arithmetic/limbs.nim
constantine/io/io_towers.nim
constantine/primitives/macro_assembler_x86.nim
tests/t_finite_fields.nim
tests/t_fp12_anti_regression.nim
tests/t_fp2_sqrt.nim

negmod_asm could introduce a non-unique representation because it only did `M-a`
https://github.com/mratsim/constantine/blob/5b1d28048601af39d4543e38231fde139d7f4010/constantine/arithmetic/assembly/limbs_asm_modular_x86.nim#L161-L185
So if a was zero, M was stored in the result.
As M ≡ 0 (mod M) this is mathematically correct and most of the time it didn't matter that we used an unreduced representation.
Except in comparison operators like `==` and `isZero`.
Closes #114 and #136
Note, there are additional changes in the macro assembler because somehow the exception tracking system now complains about exceptions in the compile-time VM.

Fuzz fix - non-unique modular representation after Assembly negate

---

benchmarks/bench_ec_g1.nim
benchmarks/bench_ec_g2.nim
benchmarks/bench_elliptic_template.nim
constantine.nimble
constantine/arithmetic/limbs.nim
constantine/elliptic/ec_shortweierstrass_affine.nim
constantine/elliptic/ec_shortweierstrass_jacobian.nim
tests/t_ec_shortw_jac_g1_mixed_add.nim
tests/t_ec_template.nim

This does the following
Jacobian coordinates are significantly more efficient on G2 than projective due to not having to deal with the Twist factors.
Surprisingly mixed addition with projective or jacobian coordinates on G1 takes the same number of cycles
Benchmark G1
Benchmark G2
This should improve the perf on the benchmarks ran by @yelhousni

Implement Jacobian mixed addition

---

README.md
benchmarks/bench_fp_double_width.nim
constantine.nimble
constantine/arithmetic/assembly/limbs_asm_modular_dbl_width_x86.nim
constantine/arithmetic/assembly/limbs_asm_modular_x86.nim
constantine/arithmetic/assembly/limbs_asm_montred_x86.nim
constantine/arithmetic/assembly/limbs_asm_montred_x86_adx_bmi2.nim
constantine/arithmetic/assembly/limbs_asm_mul_x86.nim
constantine/arithmetic/assembly/limbs_asm_mul_x86_adx_bmi2.nim
constantine/arithmetic/bigints.nim
constantine/arithmetic/finite_fields.nim
constantine/arithmetic/finite_fields_double_width.nim
constantine/arithmetic/limbs.nim
constantine/arithmetic/limbs_double_width.nim
constantine/arithmetic/limbs_montgomery.nim
constantine/config/common.nim
constantine/elliptic/ec_shortweierstrass_affine.nim
constantine/elliptic/ec_shortweierstrass_projective.nim
constantine/pairing/lines_projective.nim
constantine/primitives/extended_precision.nim
constantine/primitives/macro_assembler_x86.nim
constantine/tower_field_extensions/quadratic_extensions.nim
constantine/tower_field_extensions/tower_common.nim
constantine/tower_field_extensions/tower_instantiation.nim
metering/README.md
tests/t_bigints.nim
tests/t_finite_fields_double_width.nim
tests/t_finite_fields_vs_gmp.nim

For fast Fp2, Fp4, Fp12, implementations we should take advantage of lazy reductions, see https://github.com/mratsim/constantine/issues/15#issuecomment-640014591
However this was put on hold due to an unexplained 50 cycles difference between the theory and practice as mentioned here:
https://github.com/mratsim/constantine/blob/d12d5faf2146a895f98e74b9f5979be768e7a8cf/constantine/tower_field_extensions/quadratic_extensions.nim#L129-L139
Since we do 2 reductions, and my CPU is now running at 3.9GHz compared 4.1, we have now found out the source of the differences between theoretical cycle count and practice.
The origin is due to https://github.com/nim-lang/Nim/issues/16887 which made reduction 20 cycles slower than necessary and reduction is used twice in Fp2 multiplication.
This PR: …

FpDbl revisited

---

constantine/elliptic/ec_shortweierstrass_affine.nim
constantine/io/io_towers.nim
constantine/isogeny/frobenius.nim
constantine/pairing/lines_projective.nim
constantine/tower_field_extensions/extension_fields.nim
constantine/tower_field_extensions/tower_instantiation.nim
helpers/prng_unsafe.nim
tests/t_fp_tower_frobenius_template.nim

This drops concepts from the codebase.
Before https://github.com/nim-lang/Nim/commit/91ace2188a243b4453412ed1e79e2efcc62d95a6,
large concepts were not passed by reference like other Nim types (https://github.com/mratsim/constantine/issues/146)
While this is fixed upstream, who knows when the backports land in an actual release.
Furthermore, concepts don't have a cache in the compiler unlike generics, this leads to recompilation of concepts and also code duplication of https://github.com/mratsim/constantine/issues/27 https://github.com/nim-lang/Nim/issues/13982
Performance on 1.4.2 is as fast as concepts + latest devel
Closes #27 and closes #146 for all Nim versions.

Tower drop concepts

---

.github/workflows/ci.yml
.travis.yml
azure-pipelines.yml
tests/t_ec_sage_template.nim

How to lose an evening due to flaky tooling and bugs (https://github.com/nim-lang/RFCs/issues/300)
1. PR #155 is blocked by CI failing to clone BearSSL, a commit was removed from the tree (security issue?) https://github.com/mratsim/constantine/runs/1865343014#step:15:60
2. BearSSL is brought by a dependency chain that involves nim-json-serialization https://github.com/status-im/nim-json-serialization/issues/25
3. Nimble doesn't support task-level dependencies which makes it a pain to specify packages as optional https://github.com/nim-lang/nimble/issues/482, https://github.com/nim-lang/nimble/issues/506
4. I couldn't test Constantine as a result
1. No more workaround for https://github.com/status-im/nim-serialization/issues/33
Which required uninstalling nim-serialization before …

Drop nim-json-serialization for testing

---

constantine/pairing/mul_fp12_by_lines.nim
constantine/pairing/mul_fp6_by_lines.nim
constantine/tower_field_extensions/extension_fields.nim
constantine/tower_field_extensions/tower_instantiation.nim
tests/t_fp12_exponentiation.nim
tests/t_fp_tower_template.nim

This PR continues the work of double precision towering
- https://github.com/mratsim/constantine/pull/72
- https://github.com/mratsim/constantine/pull/144
- https://github.com/mratsim/constantine/pull/148
- https://github.com/mratsim/constantine/pull/155
Hopefully we get so efficient that even BLS24 curves become interesting.
The first commit improves Fp12 multiplication by 5%, which tranlates to about 4% speedup on pairings.

Double-precision cubic towering + pairing

---

constantine/arithmetic/assembly/limbs_asm_montred_x86_adx_bmi2.nim
constantine/arithmetic/assembly/limbs_asm_mul_x86_adx_bmi2.nim
constantine/tower_field_extensions/assembly/fp2_asm_x86_adx_bmi2.nim
constantine/tower_field_extensions/extension_fields.nim

This implements inline assembly for Fp2. Mostly it does so by having an inline export from the actual implementation.
This allows:
- the compiler to view all register usage for Fp2
- avoids multiple `hasADX` checks
Speed up is about 2% on pairings.

Assembly for Fp2

---

benchmarks/bench_fields_template.nim
constantine.nimble
constantine/arithmetic/finite_fields_square_root.nim
constantine/arithmetic/limbs_montgomery.nim
constantine/curves/bls12_381_g2_hash_to_curve.nim
constantine/ec_shortweierstrass.nim
constantine/elliptic/ec_shortweierstrass_affine.nim
constantine/elliptic/ec_shortweierstrass_jacobian.nim
constantine/hash_to_curve/cofactors.nim
constantine/hash_to_curve/h2c_hash_to_field.nim
constantine/hash_to_curve/h2c_map_to_isocurve_swu.nim
constantine/hash_to_curve/hash_to_curve.nim
constantine/hashes/h_sha256.nim
constantine/io/endians.nim
constantine/isogeny/h2c_isogeny_maps.nim
constantine/tower_field_extensions/square_root_fp2.nim
sage/derive_hash_to_curve.sage
tests/t_finite_fields_sqrt.nim
tests/t_fp_tower_frobenius_template.nim

hash-to-curve BLS12-381 perf

---

constantine.nimble
tests/t_sig_bls_lowlevel.nim

Implement low-level primitives property-based tests for BLS signature scheme (Boneh, Lynn, Shacham):
- Ethereum 2 ciphersuite `BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_` 
- BLS12-381 curve (Barreto-Lynn-Scott)
- Pubkeys on G1, Signatures on G2
- Hash function: SHA256
- Spec: https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-04

Tests for the eth2 BLS signature protocol.

---

benchmarks/bench_blueprint.nim
benchmarks/bench_fields_template.nim
benchmarks/bench_fp.nim
benchmarks/bench_fp_double_precision.nim
constantine/arithmetic/assembly/limbs_asm_montmul_x86.nim
constantine/arithmetic/assembly/limbs_asm_montmul_x86_adx_bmi2.nim
constantine/arithmetic/finite_fields_inversion.nim
constantine/arithmetic/finite_fields_square_root.nim
constantine/arithmetic/limbs_montgomery.nim
constantine/config/type_ff.nim
constantine/curves/curve25519_inversion.nim
constantine/curves/curve25519_sqrt.nim
constantine/curves/zoo_inversions.nim
constantine/curves/zoo_square_roots.nim
constantine/tower_field_extensions/assembly/fp2_asm_x86_adx_bmi2.nim
constantine/tower_field_extensions/extension_fields.nim
tests/t_finite_fields_double_precision.nim
tests/t_finite_fields_mulsquare.nim
tests/t_finite_fields_powinv.nim
tests/t_finite_fields_vs_gmp.nim

This does the following
1. Significantly improve point deserialization speed of Twisted edwards curves by implementing a generic over any prime, optimal fused sqrt+division. This is significantly faster than litterature p ≡ 5 (mod 8) only optimization _uv³(uv⁷)^((p−5)/8)_ presented in Bernstein et al paper for ED25519. 
2. Implement addition chains for inversion and sqrt of Curve25519. Note, Constantine is needlessly using Montgomery representation for the prime field. Montgomery representation is used to reduce the cost of modular reduction, but pseudo-mersenne primes in the form of 2ᵐ-c have a significantly more efficient more reduction. Modular multiplication cost could be made ~40% cheaper (https://github.com/mratsim/constantine/issues/11)
3. Rework square roots public/private proc, …

Field optimization

---

constantine/arithmetic/assembly/limbs_asm_mul_mont_x86.nim
constantine/arithmetic/assembly/limbs_asm_mul_mont_x86_adx_bmi2.nim
constantine/arithmetic/assembly/limbs_asm_redc_mont_x86.nim
constantine/arithmetic/assembly/limbs_asm_redc_mont_x86_adx_bmi2.nim
constantine/arithmetic/bigints_montgomery.nim
constantine/arithmetic/finite_fields.nim
constantine/arithmetic/finite_fields_square_root.nim
constantine/arithmetic/limbs_montgomery.nim
constantine/curves/bls12_377_sqrt.nim
constantine/curves/bls12_381_sqrt.nim
constantine/curves/bn254_nogami_sqrt.nim
constantine/curves/bn254_snarks_sqrt.nim
constantine/curves/bw6_761_sqrt.nim
constantine/elliptic/ec_shortweierstrass_projective.nim
docs/optimizations.md

This builds on top of #175 and closes #133
This accelerates reduces BLS12-381 square root computations cost by ~13.5% 
- Before 
- After 
Those are a bottleneck in:
- Signature and Public key decompression (and in Ethereum everything comes from the network compressed), https://github.com/status-im/nimbus-eth2/pull/3387#discussion_r805749053
- hashing a message to the curve for its signature and verification.
- Hence people are optimizing the heck out of it in Solidity: https://github.com/ChihChengLiang/modexp, used in this optimistic rollup project https://github.com/thehubbleproject/hubble-contracts/blob/cc3aa97d3d47b30516ad73077a8f6e8c6e834bab/contracts/libs/ModExp.sol#L332-L340
- test suite! Creating any random point for fuzzing requires either sqrt or the 5x more expensive scalar …

Low-level refactor part 2

---

.github/workflows/ci.yml
constantine.nimble
tests/t_ec_template.nim

Try 1.6 CI to debug arch specific flags issues:
- https://github.com/status-im/nim-blscurve/pull/133
- https://github.com/mratsim/Arraymancer/issues/505
- https://github.com/mratsim/Arraymancer/pull/542

try 1.6 CI

---

benchmarks/bench_poly1305.nim
benchmarks/bench_sha256.nim
constantine.nimble
constantine/hashes.nim
constantine/hashes/h_sha256.nim
constantine/mac/mac_poly1305.nim
constantine/math/arithmetic/bigints.nim
constantine/platforms/abstractions.nim
constantine/platforms/compilers/extended_precision.nim
constantine/platforms/constant_time/ct_routines.nim
constantine/platforms/primitives.nim
tests/t_mac_poly1305.nim

This adds a 1-1 translation of the spec https://datatracker.ietf.org/doc/html/rfc8439 for Poly1305.
No optimization done besides exploiting the fact that 2¹³⁰-5 is pseudo-Mersenne for fast reduction.
In particular, the last limbs has 62 bits unused which can be repurposed for an unsaturated representation that doesn't need to be slowed down by carry dependency chains.
Future TODO:
- Implement Chacha20+Poly1305 AEAD
- Optimized Poly1305 and vectorized Poly1305
- Find out how to call OpenSSL internal implementation for differential fuzzing

Poly1305 Message Authentication Code

---

benchmarks/bench_pairing_bn254_nogami.nim
benchmarks/bench_pairing_bn254_snarks.nim
benchmarks/bench_pairing_template.nim
constantine.nimble
constantine/math/curves/bls12_381_pairing.nim
constantine/math/curves/bn254_nogami_pairing.nim
constantine/math/pairing/miller_loops.nim
constantine/math/pairing/pairing_bn.nim
tests/math/t_pairing_bn254_nogami_multi.nim
tests/math/t_pairing_bn254_snarks_multi.nim

Batched multipairing:
BN254_Nogami
BN254_Snarks
This will significantly improve Codex performance for Proof-of-Retrievals over BN254_Snarks (https://github.com/status-im/nim-codex/pull/76) cc @cskiraly

Add multipairing for BN curves

---

.github/workflows/ci.yml
constantine.nimble
helpers/pararun.nim
helpers/prng_unsafe.nim
tests/math/t_bigints_mod_vs_gmp.nim
tests/math/t_bigints_mul_high_words_vs_gmp.nim
tests/math/t_bigints_mul_vs_gmp.nim
tests/math/t_finite_fields_vs_gmp.nim
tests/t_hash_sha256_vs_openssl.nim

This:
- enables parallel tests on WIndows
- enables GMP tests on Windows
- enables GMP tests on Linux 32-bit
- Fix Nim caching on all platforms to reduce bandwith impact on nim-lang.org and accelerate CI

CI: enable GMP tests on Windows and Linux 32-bit and fix caching

---

benchmarks/bench_sha256.nim
constantine/hashes/h_sha256.nim
constantine/hashes/sha256/sha256_generic.nim
constantine/hashes/sha256/sha256_x86_shaext.nim
constantine/hashes/sha256/sha256_x86_ssse3.nim
constantine/math/config/type_bigint.nim
constantine/platforms/isa/simd_x86.nim
constantine/platforms/primitives.nim
helpers/static_for.nim
tests/t_hash_sha256_vs_openssl.nim

This PR updates the SHA256 implementation
- cleanly separates message scheduling and hashing round. Message scheduling is independent of previous data and can be parallelized 4x uint32 per 4x uint32. For known padding blocks, such as those that arises in Merkle trees (see #205), it can be precomputed for significant speedups.
- implements SSSE3 (introduced in 2006, via Core 2 Duo) to parallelize message scheduling. This speeds SHA256 by 30%.
Note: the SIMD rotate instruction `_mm_ror_epi32` to trivially translate sha256 was added with AVX512F+AVX512VL.
The speedup would only be helpful on Skylake-X as the only architecture with AVX512VL but no hardware SHA (Cannon Lake never shipped). And that speedup would be limited to replacing shifts+xors with rotate
- implements hardware SHA …

Sha256 refactor

---

benchmarks/bench_ec_g1_batch.nim
benchmarks/bench_elliptic_template.nim
constantine.nimble
constantine/math/elliptic/README.md
constantine/math/elliptic/ec_shortweierstrass_affine.nim
constantine/math/elliptic/ec_shortweierstrass_batch_ops.nim
constantine/math/elliptic/ec_shortweierstrass_jacobian.nim
constantine/math/elliptic/ec_shortweierstrass_projective.nim
constantine/math/elliptic/ec_twistededwards_projective.nim
constantine/math/extension_fields/towers.nim
constantine/platforms/allocs.nim
helpers/pararun.nim
tests/math/t_ec_shortw_jac_g1_batch_add.nim
tests/math/t_ec_shortw_prj_g1_batch_add.nim
tests/math/t_ec_template.nim

This PR follows discussion at Devcon VI with @asn-d6 regarding accelerating validator pubkeys aggregation for large-scale Secret Single Leader Election.
It implements:
Perf 1M points in 180ms on my i9-11980HK (top laptop CPU from 2021)
BLST: https://github.com/mratsim/nim-blscurve/pull/1
Constantine has 33% speedup over BLST for 1000 point additions (then linear increase)

Batch additions

---

constantine.nimble
constantine/platforms/primitives.nim
constantine/platforms/threadpool/README.md
constantine/platforms/threadpool/crossthread/backoff.nim
constantine/platforms/threadpool/crossthread/taskqueues.nim
constantine/platforms/threadpool/crossthread/tasks_flowvars.nim
constantine/platforms/threadpool/docs/design.md
constantine/platforms/threadpool/parallel_offloading.nim
constantine/platforms/threadpool/threadpool.nim

This removes a significant threadpool perf pessimization introduced in #222
- reserve threads are removed.
- some perf was also lost because:
- `primitives.nim` was imported and it needed globals for CPU features detection. Unsure how this exactly slowed a benchmark down though.
- creating a task is inlined for spawn (but not for loops as those requires more initialization)
- the conditional branch in `sync` was a debugging aid and is not needed
An additional slight optimization is avoiding syscalls in `wake` when we have sleepy workers that are not yet asleep. The change in epoch is sufficient to avoid their sleep.
Finally, the stealHalf and adaptative theft policy code has been removed as it was never finished.

[Threadpool] Remove reserve threads

---

constantine/math/arithmetic/limbs_montgomery.nim
constantine/math_arbitrary_precision/arithmetic/bigints_views.nim
tests/math_fields/t_io_fields.nim

From the Ethereum Foundation sponsored fuzzing by @guidovranken (linked to #54),
``fromBig`` can lead to incorrectly reduced field elements.
This is because classic Montgomery reduction can reduce inputs from the range [0, 4p²) -> [0, p)  but this is not the case with the no-carry optimization from Gnark (https://hackmd.io/@gnark/modular_multiplication and https://eprint.iacr.org/2022/1400.pdf section 2)
In practice ``getMont`` and ``fromBig`` are internal-only procedures that only deserialized well-formed inputs that have been pre-checked in protocols:
- https://github.com/mratsim/constantine/blob/151f284da6caad1545a38f871c421c5bb2da8f6a/constantine/ethereum_bls_signatures.nim#L284-L293
- https://github.com/mratsim/constantine/blob/151f284da6caad1545a38f871c421c5bb2da8f6a/constantine/ethe …

Fix fuzz 1 failure: incorrect reduction of BigInt

---

constantine.nimble
constantine/hash_to_curve/hash_to_curve.nim
constantine/math/elliptic/ec_shortweierstrass_jacobian.nim
constantine/math/extension_fields/towers.nim
tests/t_hash_to_curve_random.nim

Skipping the final substraction in this codepath (only taken for EC add on isogeny in SSWU hash-to-curve): https://github.com/mratsim/constantine/blob/d0f4ad8cdaf5fbbec98889bfcfb3a04082ff6f94/constantine/math/elliptic/ec_shortweierstrass_jacobian.nim#L292
is incorrect as `HHH_or_Mpre` is later used in field addition/substraction and so need fully reduced Montgomery representation.
Furthermore we fix a similar bug when the curve has a coefficient a=-3 (we have no such curve fully implemented though P256 and other NIST curves all have a=-3).
Lastly we accelerate BLS12-381 hashToG2 by enabling `mulCheckSparse`
We also change the notation of intermediate point from P to Q to be in line with the spec documentation

Fuzz Fix - Hash-To-Curve - Isogeny EC add non-fully-reduced input

---

constantine/math/elliptic/ec_twistededwards_projective.nim
constantine/math/io/io_ec.nim

Fixes #260 
For affine points, Projective types were getting used (fixed in this PR)
https://github.com/mratsim/constantine/blob/ad04e6ea573e7d5de3e03edc60f40114f1fe5050/constantine/math/elliptic/ec_twistededwards_projective.nim#L297
No support was there for TwistedEdwards curve in `toHex()` ( fixed in this PR )
https://github.com/mratsim/constantine/blob/ad04e6ea573e7d5de3e03edc60f40114f1fe5050/constantine/math/io/io_ec.nim#L31

fix: support for ECP_TwEdwards in toHex()

---

constantine.nimble
constantine/ethereum_verkle_primitives.nim
constantine/math/elliptic/ec_twistededwards_batch_ops.nim
tests/t_banderwagon.nim
tests/t_ethereum_verkle_primitives.nim

Fixes #277 
Refere the issue #277 for the detailed specs

`MapToScalarField()` added for Banderwagon points

---

constantine.nimble

By default, nimble strips anything not named `constantine` but we need `metering` as well.
This adapt the nimble file to allow this.
Note: the current directory structure was chosen after careful consideration to market across devs looking for different capabilities in cryptographic backend. Metering is a particularly valuable niche to optimize EVM gas costs hence it SHOULD be "in-your-face" in the directory structure.
We might also want to consider installing the binding generators, but it's unsure if there is a command (maybe `nimble build`?) to build Constantine as a static or shared library. Though that might not be needed in the future with incremental compilation.
Lastly we might also consider installing the tests so they can be run on constantine install, it's especially important …

Allow installation / import through nimble

---

constantine/platforms/code_generator/bindings/llvm_abi.nim
constantine/platforms/code_generator/ir.nim
constantine/platforms/code_generator/llvm.nim
constantine/platforms/code_generator/nvidia_inlineasm.nim

This fixes the Nvidia JIT backend
- #239 moved an `unmarshal` proc to `constantine/serialization/io_limbs` that is needed for BigNums https://github.com/mratsim/constantine/blob/4ccd8aaab86f0c1955125a5ce6fe66915cb2cbf4/constantine/platforms/code_generator/ir.nim#L91-L95
- Warning about unused `ctx` in the Nvidia assembly code generator when regTy takes a branch that doesn't use `ctx`
- Warning about unnecesary conversion from a type to itself
- LLVM 16 deleted some optimization passes or moved them to another name

Nvidia JIT fixes

---

.github/workflows/ci.yml
benchmarks/bench_blueprint.nim
benchmarks/bench_evm_modexp_dos.nim
benchmarks/bench_fp_double_precision.nim
constantine/ethereum_evm_precompiles.nim
constantine/math/arithmetic/finite_fields_double_precision.nim
constantine/platforms/abstractions.nim
constantine/platforms/config.nim
constantine/platforms/constant_time/ct_types.nim
constantine/platforms/constant_time/multiplexers.nim
constantine/platforms/intrinsics/addcarry_subborrow.nim
constantine/platforms/intrinsics/bitops.nim
constantine/platforms/intrinsics/extended_precision.nim
constantine/platforms/intrinsics/extended_precision_64bit_uint128.nim
constantine/platforms/intrinsics/extended_precision_vartime.nim
constantine/platforms/isa/macro_assembler_x86.nim
constantine/platforms/isa/macro_assembler_x86_att.nim
constantine/platforms/isa/macro_assembler_x86_intel.nim
constantine/platforms/primitives.nim
tests/math_arbitrary_precision/t_bigints_mod.nim
tests/t_ethereum_evm_modexp.nim

Raised in Google OSS Fuzz
The fixes introduced by #286 didn't compile on 32-bit, this should fix that.
Additionally, we check if #244 was fixed upstream by CI agents with newer packages, and so add back 32-bit tests to CI.
cc @guidovranken

32-bit fixes

---

constantine/math/io/io_bigints.nim
tests/math_bigints/t_io_bigints.nim

Allows `BigInt.fromHex()` to work with both little-endian and big-endian hex strings.

Conversion of little endian hex strings to bigints

---

constantine-rust/constantine-sys/build.rs
constantine-rust/constantine-zal-halo2kzg/src/lib.rs

https://github.com/privacy-scaling-explorations/halo2curves/pull/107#issuecomment-1841456570
For CPU only and because Constantine can work directly in projective coordinates like Halo2curves, we don't really need the caching API so it's just forwarding everything to the MSM.
Though technically we might want to implement Fr (Montgomery repr) -> Bigint (canonical repr) in the scalar descriptors.

Rust: Add tentative caching API for ZAL

---

constantine-rust/constantine-sys/src/bindings.rs
constantine/serialization/codecs_bls12_381.nim
include/constantine.h
include/constantine/curves/bls12_381_codecs.h

This exports the Zcash serialization for BLS12-381 scalar and curve elements.
Requested by @Armantidas for https://github.com/lynxcs/rust-kzg/commit/c7930bdc3afb3b0e3cccc9958aefbfe7e723fe1f to add a Constantine-based KZG backend to https://github.com/sifraitech/rust-kzg

Export BLS12-381 serialization/deserialization to C/Rust

---

constantine.nimble

added -fPIC when using make_lib_rust, since [rust already does that by default.](https://github.com/rust-lang/rust/pull/16340)
This change is required by [rust-kzg constantine backend](https://github.com/sifraitech/rust-kzg/pull/251) to make c-kzg-4844 bindings work.
@mratsim if enabling for all rust builds is not acceptable, I can also add as optional feature in Cargo.toml & change how it's passed in build.rs
I am not familiar with Nim so if there's a better/more preferred way of doing this lmk, will be happy to fix.

make_lib_rust - use position independent code

---

constantine.nimble
constantine/math/elliptic/ec_endomorphism_accel.nim
constantine/math/elliptic/ec_multi_scalar_mul_parallel.nim
tests/math_elliptic_curves/t_ec_sage_template.nim
tests/math_elliptic_curves/t_ec_shortw_prj_edge_case_345.nim
tests/math_elliptic_curves/t_ec_template.nim

This tentatively fixes #345 with the simple approach explained in https://github.com/mratsim/constantine/issues/345#issuecomment-1899372371 to add an extra bit to hold the decomposed miniscalars.
This will be kept as a fix if we can also relax the requirement for exact bit match for `scalarMul_vartime` when dispatching to endomorphism.
https://github.com/mratsim/constantine/blob/dbd2630daa6d599a9e78ad247e6858baf41664da/constantine/math/elliptic/ec_scalar_mul_vartime.nim#L353-L377
In that case, we can remove the current way to handle negative mini-scalars by negating the curve point.

Tentative fix for #345 - constant-time scalar mul with endomorphism acceleration wrong result

---

constantine/math_codegen/fields_nvidia.nim
constantine/platforms/code_generator/ir.nim
constantine/platforms/code_generator/nvidia.nim
constantine/platforms/code_generator/nvidia_inlineasm.nim
constantine/platforms/isa/macro_assembler_x86_att.nim
constantine/platforms/isa/macro_assembler_x86_intel.nim
docs/crypto-nvidia_gpus.md
tests/gpu/t_nvidia_fp.nim

This PR adds:
- field substraction
- field multiplication for curve with an spare bit
This ups the minimum requirement to Cuda 11.5.1 to ensure 32-bit fused-multiply-add "hi" works properly: https://forums.developer.nvidia.com/t/wrong-result-returned-by-madc-hi-u64-ptx-instruction-for-specific-operands/196094
Also, using 64-bit arithmetic on GPU will give wrong results due to: https://forums.developer.nvidia.com/t/incorrect-result-of-ptx-code/221067

Nvidia GPU: field substraction and multiplication

---

constantine/math/arithmetic/finite_fields.nim
constantine/math/constants/bandersnatch_sqrt.nim
constantine/math/constants/banderwagon_sqrt.nim
constantine/math/constants/zoo_square_roots.nim

This implements a low-hanging fruit addition chain for square root for Bandersnatch and Banderwagon so that #354 is benched against fully optimized Tonelli-Shanks.
cc @advaita-saha

Square Root: addition chain for Bandersnatch and banderwagon

---

benchmarks/bench_fields_template.nim
benchmarks/bench_fp.nim
constantine/math/arithmetic/finite_fields_square_root.nim
constantine/math/arithmetic/finite_fields_square_root_precomp.nim
constantine/math/constants/bandersnatch_sqrt.nim

This builds on top of #354 and #356 to bring a further 20% perf improvement to Bandersnatch/Banderwagon square root and point deserialization.
The technique was hinted at in this comment: https://github.com/mratsim/constantine/pull/354#discussion_r1485112409
This is the first part of a larger refactoring to make the square root via discrete log constant-time (#358) and introduce a sage script for constant generation (#359)
Note: as this is only tested in verkle trees test, and those are not in nimble yet (pending #330), the local test must be:
```
nim c -r --outdir:build tests/t_ethereum_verkle_primitives.nim
```

sqrt-via-dlog: cleanup and 20% accel for vartime Bandersnatch/Banderwagon deserialization

---

benchmarks/bench_verkle_primitives.nim
constantine/serialization/codecs_banderwagon.nim
tests/t_ethereum_verkle_primitives.nim

Fixes #317 
Adds the uncompressed point serialisation and deserialisation, which would be further needed in nim-eth-verkle for VerkleNode serialization

Add Uncompressed Serde

---

constantine/serialization/codecs_banderwagon.nim
tests/t_ethereum_verkle_primitives.nim

Adds BatchSerialisation in Uncompressed format.
Needed for LeafNode serialisation in `nim-eth-verkle`

BatchSerialization for Uncompressed Points

---

.github/workflows/ci.yml

pending upstream https://github.com/nim-lang/Nim/issues/23547 and https://github.com/nim-lang/nightlies/pull/82
Internal issues: #373 #372 and PR #374

ci: temporarily deactivate non-working CI 

---

benchmarks/bench_eth_evm_precompiles.nim
constantine/ethereum_evm_precompiles.nim
tests/t_ethereum_evm_precompiles.nim

This adds a benchmark for BN254 precompiles and support for SHA256 precompile.
Bench on Ryzen 7840U
```
CC=clang nimble bench_eth_evm_precompiles
```
```
--------------------------------------------------------------------------------------------------------------------------------
SHA256 -  32 bytes            72 gas    2117.65 MGas/s    29411764.706 ops/s           34 ns/op          114 CPU cycles (approx)
SHA256 -  64 bytes            84 gas    1714.29 MGas/s    20408163.265 ops/s           49 ns/op          161 CPU cycles (approx)
SHA256 -  96 bytes            96 gas    1959.18 MGas/s    20408163.265 ops/s           49 ns/op          163 CPU cycles (approx)
SHA256 - 128 bytes           108 gas    1459.46 MGas/s    13513513.514 ops/s           74 ns/op          245 CPU cycles (approx) …
```

EVM precompiles - SHA256 and BN254

---

constantine-rust/constantine-halo2-zal/Cargo.toml
constantine-rust/constantine-halo2-zal/src/lib.rs
constantine-rust/constantine-halo2-zal/tests/t_zal_msm_accel.rs

Replaces the dependency for the MSM acceleration layer to use the version from the Privacy Scaling Explorations repo (https://github.com/privacy-scaling-explorations/halo2/)
Still needs to depend on `halo2curves` explicitly, as `halo2_middleware` does not reexport it (and currently I didn't manage to figure out how to fix that).

update dependency for halo2 MsmAccel trait

---

bindings/lib_constantine.nim
constantine/ethereum_bls_signatures.nim
constantine/ethereum_bls_signatures_parallel.nim
constantine/signatures/bls_signatures.nim
examples-c/README.md
examples-c/ethereum_bls_signatures.c
include/constantine.h
include/constantine/protocols/ethereum_bls_signatures.h
include/constantine/protocols/ethereum_bls_signatures_parallel.h

Adds the C API for BLS signature `aggregate_verify` and `batch_verify` functions. The parallel version using a threadpool is also exposed.
Note: For the batched API we currently provide a `ByteView` typedef on the C side (happy to choose a different name, probably better snake_case and lower case, maybe `ctt_byte_view` ?). We _could_ do an anonymous struct in the function signatures, but at least I'm not aware of a way to get around 'incompatible pointer' warnings with GCC / Clang in that case.
It includes 2 minor fixes for the `batch_verify(_parallel)` Nim C targeted procs. They were accidentally generic and missing a `toOpenArray` for the `messages`. In addition it fixes a minor bug in the `update` proc for the `View[byte]` overload, which lead to an infinite recursion.

C API for BLS signature `aggregate_verify` & `batch_verify` (incl parallel)

---

README.md
bindings/lib_constantine.nim
constantine/ethereum_evm_precompiles.nim
examples-c/ethereum_bls_signatures.c
examples-c/ethereum_evm_precompiles.c
include/constantine.h
include/constantine/protocols/ethereum_evm_precompiles.h

This is based on and continues from #381. It now also adds a C API for the EVM precompiles module.
One example is added that generally checks the API works and it includes a test case from:
https://github.com/mratsim/constantine/blob/master/tests/protocol_ethereum_evm_precompiles/eip-2537/map_fp2_to_G2_bls.json
which passes as expected.

C API for EVM precompiles

---

constantine.nimble
constantine/eth_verkle_ipa/ipa_prover.nim
constantine/eth_verkle_ipa/ipa_verifier.nim
constantine/eth_verkle_ipa/multiproof.nim
tests/t_ethereum_verkle_ipa_primitives.nim

This is #330, rebased to latest master and for investigation of CI failure on Windows

PR #330 - enable test verkle ipa

---

README.md
constantine-go/constantine.go
constantine-go/constantine_test.go

This continues from #383 by porting over the EVM precompiles C API into Go. All test cases are ported from Nim and should all pass.

Go API for EVM precompiles

---

ARCHITECTURE.md
benchmarks/bench_eth_eip4844_kzg.nim
constantine-go/constantine.go
constantine-go/constantine_test.go
constantine-rust/constantine-ethereum-kzg/src/lib.rs
constantine-rust/constantine-ethereum-kzg/tests/t_ethereum_kzg_vectors.rs
constantine-rust/constantine-sys/src/bindings32.rs
constantine-rust/constantine-sys/src/bindings64.rs
constantine/commitments/kzg_polynomial_commitments.nim
constantine/commitments/kzg_polynomial_commitments_parallel.nim
constantine/commitments_setups/ethereum_kzg_srs.nim
constantine/eth_verkle_ipa/ipa_prover.nim
constantine/eth_verkle_ipa/ipa_verifier.nim
constantine/eth_verkle_ipa/multiproof.nim
constantine/ethereum_eip4844_kzg.nim
constantine/ethereum_eip4844_kzg_parallel.nim
constantine/math/polynomials/polynomials.nim
constantine/math/polynomials/polynomials_parallel.nim
include/constantine/protocols/ethereum_eip4844_kzg_parallel.h
tests/t_ethereum_eip4844_deneb_kzg_parallel.nim
tests/t_ethereum_verkle_ipa_primitives.nim

This changes the threadpool to always be first argument. It is the most "global" of the context, because it's at library/app level and not just KZG or BLS signatures.
As powers-of-tau and polynomial domains are also contexts, they are moved in front and this impacts KZG and IPA modules.
Furthermore, document the API.
It is inspired by libsecp256k1:
- https://github.com/bitcoin-core/secp256k1/blob/v0.5.0/include/secp256k1.h#L10-L25
This breaks Nim, C, Go, Rust API and should be done now before we cut the first ever Constantine release.
This impacts Grandine's branch: https://github.com/mratsim/constantine/pull/331

API: argument order (breaking external Nim/C/Go/Rust EIP-4844 API

---

constantine-go/constantine.go
constantine-go/constantine_test.go

These two were inconsistent in their naming compared to the rest of the functions, which all use `Kzg` instead.

[Go] rename 2 functions in Go API using KZG -> Kzg

---

constantine/proof_systems/constraint_systems/r1cs_circom_parser.nim

We were accidentally still using `readChars` in the parser instead of our constantine internal `readInto`.

[R1CS] Fix parsing of R1CS files using `readChars`

---

constantine/commitments/eth_verkle_ipa.nim
constantine/math/polynomials/polynomials.nim
tests/t_ethereum_verkle_ipa_primitives.nim

Follow-up on #397.
The size of the array for IPA verification was off-by-one.
With the address sanitizer the last cell was zero-init , hence we had a correct result. This was not the case with normal allocator.

refactor(verkle-ipa): fix off-by-one, reenable simple prover+verifier test

---

.github/workflows/ci.yml

- Disabled in https://github.com/mratsim/constantine/pull/375
- Regression reverted in backport in https://github.com/nim-lang/Nim/commit/767a901267c782765e010d106fae277b27e04981

reenable nim v2.0.x in CI

---

constantine.nimble
constantine/math/elliptic/ec_endomorphism_accel.nim
constantine/math/elliptic/ec_multi_scalar_mul.nim
constantine/math/elliptic/ec_multi_scalar_mul_parallel.nim
constantine/math/elliptic/ec_scalar_mul_vartime.nim
constantine/math/elliptic/ec_twistededwards_affine.nim
constantine/named/constants/bandersnatch_endomorphisms.nim
constantine/named/constants/banderwagon_endomorphisms.nim
constantine/named/constants/bls12_377_subgroups.nim
constantine/named/constants/bls12_381_subgroups.nim
constantine/named/constants/bn254_nogami_subgroups.nim
constantine/named/constants/bn254_snarks_subgroups.nim
constantine/named/constants/bw6_761_subgroups.nim
constantine/named/properties_fields.nim
constantine/named/zoo_endomorphisms.nim
sage/derive_endomorphisms_bandersnatch.sage
tests/math_elliptic_curves/t_ec_shortw_jac_g1_mul_endomorphism_bls12_381.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g1_mul_endomorphism_bn254_snarks.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g2_mul_endomorphism_bls12_381.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g2_mul_endomorphism_bn254_snarks.nim
tests/math_elliptic_curves/t_ec_template.nim
tests/math_elliptic_curves/t_ec_twedwards_mul_endomorphism_bandersnatch.nim
tests/math_fields/t_finite_fields_vs_gmp.nim

Replaces #380, rebased on top of #402 to provide 
The PR needs extra tests and benchmarks but has been pending for 2 months so merging with acceleration deactivated.

 Bandersnatch/banderwagon endomorphism acceleration v2

---

config.nims
constantine/commitments/eth_verkle_ipa.nim
constantine/commitments/pedersen_commitments.nim
constantine/math/elliptic/ec_multi_scalar_mul.nim
constantine/math/elliptic/ec_multi_scalar_mul_parallel.nim
constantine/math/elliptic/ec_twistededwards_projective.nim
constantine/named/README.md
constantine/named/config_fields_and_curves.nim

There were 2 bugs leading to wrong result in Twisted Edwards MSM in #390.
1. The equality checks should special case neutral elements or a neutral element will be considered equal.
2. In MSM, we should initialize buckets to the neutral element not via `zeroMem` which lead to invalid computation for Twisted Edwards curves. This fixes #390. Unfortunately it doesn't seem to help for #366

Twisted Edwards MSM: `setNeutral` instead of zeroMem

---

constantine/ethereum_evm_precompiles.nim

fix(eip-2537): memory leak on invalid input deserialization

---

constantine.nimble
constantine/math/elliptic/ec_multi_scalar_mul.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g2_msm_bug_366.nim

This fixes #366
Here is the sequence of events.
- 22529 input coefficients of size 254 bits
- After endomorphism computation, they are transformed into 90116 coefficients of size 65 bits
- 90116 maps to an MSM parameter c of 13
- 13 divides 65 exactly and triggers a bug where 1 mini-MSM iteration is missing.

fix(MSM - #366): edge case when scalar bits are divided by MSM 'c' parameter

---

tests/t_ethereum_verkle_ipa_primitives.nim

Addresses #396 ,
Fixes IPA consistency test, now the test returns the correct `prover_challenge` post `ipa_prove`, and then correctly verifies the same correctly as well.
For reference, https://github.com/crate-crypto/verkle-trie-ref/blob/2332ab8/ipa/ipa_test.py#L38-L50.
Also removed the `compile with address sanitizer ON` message, as that bug has been now fixed here #403

fixed IPA consistency test, rm addressSanitizer message

---

ARCHITECTURE.md
PLANNING.md
constantine/hash_to_curve/hash_to_curve.nim
constantine/lowlevel_elliptic_curves.nim
constantine/lowlevel_fields.nim
constantine/math/arithmetic/finite_fields.nim
constantine/math/elliptic/ec_scalar_mul.nim
constantine/math/elliptic/ec_scalar_mul_vartime.nim
constantine/math/elliptic/ec_shortweierstrass_jacobian.nim
constantine/math/elliptic/ec_shortweierstrass_projective.nim
constantine/math/elliptic/ec_twistededwards_projective.nim
constantine/math/extension_fields/towers.nim
constantine/math/polynomials/polynomials.nim
constantine/math/polynomials/polynomials_parallel.nim
tests/math_fields/t_finite_fields.nim

This adds out of place syntactic sugar for finite fields (FF), extension fields and elliptic curves (EC):
- `+` for addition
- `~+` for variable time addition (EC only)
- `-` and `~-`
- `*` for multiplication (FF) and scalar multiplication (EC)
- `~*` for variable time scalar multiplication (EC)
Due to performance issues (useless **large** copies and extra stack alloc instead of in-place construction) https://github.com/mratsim/constantine/issues/145, they should be avoided for internal protocols.
However they are convenient for rapid prototyping, debugging and testing as they skip variable and type declaration.

feat(ux): out-of-place syntactic sugar

---

constantine.nimble
constantine/math/elliptic/ec_endomorphism_accel.nim
constantine/math/elliptic/ec_multi_scalar_mul.nim
constantine/math/elliptic/ec_multi_scalar_mul_parallel.nim
constantine/math/elliptic/ec_scalar_mul.nim
constantine/math/elliptic/ec_scalar_mul_vartime.nim
constantine/named/zoo_endomorphisms.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g1_mul_endomorphism_bls12_381.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g1_mul_endomorphism_bn254_snarks.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g2_mul_endomorphism_bls12_381.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g2_mul_endomorphism_bn254_snarks.nim
tests/math_elliptic_curves/t_ec_template.nim

This PR:
- fixes endomorphism acceleration when the multiplicand bits are not exactly the scalar field bits. The mini-scalar were not big enough in intermediate computation.
- enable Bandersnatch and Banderwagon endomorphism following #405
Note: for MSM, Bandersnatch and Banderwagon are not using endomorphisms.
This is because contrary to Short Weierstrass curves, we need to switch to projective coordinates to efficiently compute Bandersnatch/wagon endomorphism.
Closes #298

fix(ec): non canonical endomorphism acceleration

---

constantine/ethereum_evm_precompiles.nim
constantine/serialization/io_limbs.nim
tests/t_ethereum_evm_precompiles.nim

I encountered 3 issues working on the updated Go / Rust APIs. The (now more) static nature of the Go API (using fixed size arrays) showed me that (at least) one case succeeds that is supposed to fail. That test case is:
https://github.com/mratsim/constantine/blob/master/tests/protocol_ethereum_evm_precompiles/eip-2537/fail-add_G1_bls.json#L27-L31
The test is supposed to fail, because the X coordinate of the first point given in the input is way larger than the prime field size (see the string starting with a `10` byte). Investigating led me to realize that the BigInt parsing logic ignored the `false` return value of the `unmarshal`. The actual `unmarshal` call failed with the intended error that the size is too large for the target BigInt. But because we ignored that return value, the …

Fix `unmarshal` bugs

---

tests/t_ethereum_verkle_ipa_primitives.nim

Adds a Verkle multiproof consistency test, a continuation to addressing issue #396, implements the test https://github.com/crate-crypto/go-ipa/blob/b1e8a79/multiproof_test.go#L63-L132 as per the Verkle trie spec
Skips ipa_multi_verify because of a potential bug in `g2t`, will be addressed and fixed in successive PRs

add: multiproof consistency test

---

constantine/math/elliptic/ec_scalar_mul_vartime.nim

Another minor issue I encountered playing around with moonmath's BLS6-6. The code previously accidentally only returned 3 for the case 5 using `X.scalarMul_vartime(5)`.
I noticed it when comparing manual addition of the generator vs scalar multiplication, in order to construct all elements of the G1 subgroup:
```nim
let fx = Fp[BLS6_6].fromUint(13'u32)
let fy = Fp[BLS6_6].fromUint(15'u32)
var gen {.noinit.}: EC_ShortW_Aff[Fp[BLS6_6], G1]
gen.x = fx
gen.y = fy
let genJ = gen.getJacobian()
var curA = genJ
for i in 1 .. 13:
let x = BigInt[6].fromUint(i.uint32)
var cur = genJ
cur.scalarMul_vartime(x) # <- element 5 returned element 3 before this fix
echo "Index: ", i, " [i] g = ", cur.toDecimal() # (I added `toDecimal for EC points)
echo "Addition: ", curA.toDecimal()
echo …
```

fix `scalarMul_vartime` for tiny multiple 5

---

README-PERFORMANCE.md
README.md
benchmarks/bench_fields_template.nim
benchmarks/bench_fp.nim
benchmarks/bench_gt.nim
benchmarks/bench_gt_template.nim
constantine.nimble
constantine/math/elliptic/ec_endomorphism_accel.nim
constantine/math/elliptic/ec_multi_scalar_mul.nim
constantine/math/elliptic/ec_multi_scalar_mul_parallel.nim
constantine/math/elliptic/ec_scalar_mul_vartime.nim
constantine/math/extension_fields/towers.nim
constantine/math/pairings/gt_exponentiations_vartime.nim
constantine/named/zoo_endomorphisms.nim
sage/derive_endomorphisms.sage
sage/derive_frobenius.sage
tests/math_pairings/t_pairing_bls12_381_gt_exp.nim
tests/math_pairings/t_pairing_bn254_snarks_gt_exp.nim
tests/math_pairings/t_pairing_template.nim

This PR adds a performance baseline for Whisk in GT.
https://ethresear.ch/t/the-return-of-torus-based-cryptography-whisk-and-curdleproof-in-the-target-group/16678
Here is the speed on a 7840U:
For comparison here is scalar mul on G1
and on G2
Hence exponentiation in Gt (131 us) is within 30% of scalar mul in G2 (96 us).
cc @asanso

𝔾ₜ exponentiation, with endomorphism acceleration

---

constantine/lowlevel_bigints.nim
constantine/lowlevel_fields.nim
constantine/lowlevel_pairing_curves.nim
constantine/math/arithmetic/bigints.nim
constantine/math/arithmetic/finite_fields.nim
constantine/math/elliptic/ec_scalar_mul.nim
constantine/math/pairings/gt_exponentiations.nim
constantine/named/properties_curves.nim
constantine/platforms/allocs.nim

Constantine is continuously fuzzed on Google OSS-Fuzz through CryptoFuzz.
The test harness is https://github.com/guidovranken/cryptofuzz/blob/042cac0727b99a39dfecfd61d994f5972e2e7e3d/modules/constantine/constantine_harness.nim and has been broken by refactoring preceding the v0.1.0 release:
- https://github.com/mratsim/constantine/pull/399
- https://github.com/mratsim/constantine/pull/400
- https://github.com/mratsim/constantine/pull/402
This PR:
- exposes everything cryptofuzz tests in the `lowlevel_*.nim` files so that it doesn't depend on internal folder structure.
- remove the new CastSizes warning when raw casting between integer of different size for allocation.
- exposes new pow/pow_vartime by a finite field and out-of-place using `^` and `~^`
It also fails to enable creating a …

fix(cryptofuzz): expose all cryptofuzz tested primitives in lowlevel_*

---

constantine/math/arithmetic/limbs_exgcd.nim
tests/math_bigints/t_bigints.nim
tests/math_fields/t_finite_fields_powinv.nim

Constantine implements a fused inversion+multiply (FIM) that does `FIM(a, F, p) = F.a⁻¹ (mod p)` 
This allows inversion in the Montgomery domain without converting back-and-forth in the canonical representation.
As a reminder, in the Montgomery domain we map a to a' with `a' = aR (mod p)` with R a magic constant, for example for `Fr[BLS12_381]` which is 255 bits,  `R = 2⁶⁴*⁴ (mod p)` i.e. the next multiple of the word size that can fully store the modulus p.
Hence `a'⁻¹ = a⁻¹R (mod p) = (aR)⁻¹.R² (mod p) = FIM(a', R², p)`
Unfortunately the code was shortcutting when `a' == 1` to 1 instead of F.
https://github.com/mratsim/constantine/blob/9a2d23b1e718664d54068a2f374d31e91418ca27/constantine/math/arithmetic/limbs_exgcd.nim#L844-L858
Fortunately at the protocol-level Constantine only uses …

fix(arith): bug in vartime inversion when using fused inverse+multiply by factor - found by Guido Vranken

---

constantine/math/endomorphisms/split_scalars.nim
constantine/math/extension_fields/towers.nim

A significant amount of upstream bugs and regressions have been fixed and backported related to statics, generics and templates which Constantine uses heavily.
- https://github.com/nim-lang/Nim/issues/22947
- https://github.com/nim-lang/Nim/issues/23711
- https://github.com/nim-lang/Nim/issues/23755
- https://github.com/nim-lang/Nim/issues/23784
This PR works around the last one that prevent Constantine from compiling on devel:
- https://github.com/nim-lang/Nim/issues/23547
In summary the following cause a type mismatch:
```Nim
func mulCheckSparse*(a: var QuadraticExt, b: static QuadraticExt) {.inline.} =
```
but the following works
```Nim
template mulCheckSparse*(a: var QuadraticExt, b: QuadraticExt) =
```
However there were 2 template symbol generations issue:
- one that was fixed in …

Compatibility with Nim v1.6.x, Nim v2.0.x, Nim v2.2.x

---

constantine/platforms/intrinsics/addcarry_subborrow.nim

GCC 14 made passing an "incompatible" pointer type to another function an error.
- https://gcc.gnu.org/gcc-14/porting_to.html#c
- https://gcc.gnu.org/pipermail/gcc-cvs/2023-December/394351.html
The issue comes from builtin add-carry and sub-borrow.
Nim `uint64` maps to `NU64` which itself maps to `uint64_t` which itself maps to `long unsigned int` on x86-64.
However `_addcarry_u64` has for signature `unsigned char _addcarry_u64 (unsigned char c_in, unsigned __int64 a, unsigned __int64 b, unsigned __int64 * out)`
`unsigned __int64` maps to `unsigned long long` which is deemed incompatible with `uint64_t` so we need an explicit cast.

fix(gcc): compatibility with GCC14

---

constantine.nimble
constantine/named/deriv/parser_curves.nim
constantine/platforms/intrinsics/addcarry_subborrow.nim
constantine/platforms/x86/macro_assembler_x86_att.nim
tests/math_extension_fields/t_fp_tower_template.nim
tests/math_fields/t_finite_fields.nim
tests/math_fields/t_finite_fields_mulsquare.nim
tests/math_fields/t_finite_fields_vs_gmp.nim

This fixes compilation in 32-bit mode on 64-bit machines. And fixes the C definition of 32-bit add-carry intrinsics.
It also updates some test to use the new names following #402
Lastly we kept having "code after noReturn" section in the VM in the curve parser

fix: 32-bit on 64-bit compilation

---

benchmarks/bench_ec_g1.nim
benchmarks/bench_ec_g1_scalar_mul.nim
benchmarks/bench_ec_g2_scalar_mul.nim
benchmarks/bench_elliptic_parallel_template.nim
constantine.nimble
constantine/math/arithmetic/finite_fields.nim
constantine/math/elliptic/ec_multi_scalar_mul_parallel.nim
constantine/named/constants/secp256k1_endomorphisms.nim
constantine/named/zoo_endomorphisms.nim
sage/curves.sage
sage/derive_endomorphisms.sage
sage/testgen_scalar_mul.sage
tests/math_elliptic_curves/t_ec_sage_secp256k1.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g1_add_double.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g1_mixed_add.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g1_mul_distri.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g1_mul_sanity.nim
tests/math_elliptic_curves/t_ec_shortw_jac_g1_mul_vs_ref.nim
tests/math_elliptic_curves/t_ec_shortw_jacext_g1_add_double.nim
tests/math_elliptic_curves/t_ec_shortw_jacext_g1_mixed_add.nim
tests/math_elliptic_curves/t_ec_shortw_prj_g1_add_double.nim
tests/math_elliptic_curves/t_ec_shortw_prj_g1_mixed_add.nim
tests/math_elliptic_curves/t_ec_shortw_prj_g1_mul_distri.nim
tests/math_elliptic_curves/t_ec_shortw_prj_g1_mul_sanity.nim
tests/math_elliptic_curves/t_ec_shortw_prj_g1_mul_vs_ref.nim
tests/math_elliptic_curves/vectors/tv_Secp256k1_scalar_mul_G1_128bit.json
tests/math_elliptic_curves/vectors/tv_Secp256k1_scalar_mul_G1_256bit.json
tests/math_elliptic_curves/vectors/tv_Secp256k1_scalar_mul_G1_32bit.json
tests/math_elliptic_curves/vectors/tv_Secp256k1_scalar_mul_G1_64bit.json

This is the first of a series of PR to bring secp256k1 performance to state-of-the-art and then beyond.
See overall steps in #285.
Unfortunately the most important primitive field multiplication does not use assembly for secp256k1 (256-bit) at the moment. Hence the huge gap (~30%) with the Pallas curve (255-bit) for example.

feat(secp256k1): add endomorphism acceleration

---

constantine/math_compiler/ir.nim
research/codegen/nim.cfg
research/codegen/x86_inlineasm.nim
research/codegen/x86_instr.nim
research/codegen/x86_poc.nim

This updates the research on adding an x86 backend to our LLVM bindings following #402.
Furthermore this tests whether it's possible to create pure assembly .S files without Nim so that:
- It's easier to integrate in C/Rust/Go as we remove the Nim toolchain
- It's possible to reduce generate all code in the same LLVM module to ensure inter-procedural optimization, constant inlining and deduplication.
- We don't depend on GCC codegen quality which is bad for big integers/cryptography
Unfortunately there is a showstopper:
- We cannot use inline assembly and so ADOX/ADCX to print assembly
And a couple of annoying part:
- If we fix the showstopper, we need to be able to clear the eflags (carry, overflow, sign, zero, ...)
This is usually done by `xor` but it will be optimized away by the …

research: update LLVM x86 compiler and JIT

---

constantine/math_compiler/codegen_amdgpu.nim
constantine/math_compiler/codegen_nvidia.nim
constantine/platforms/abis/amdcomgr_abi.nim
constantine/platforms/abis/amdgpu_abi.nim
constantine/platforms/abis/c_abi.nim
constantine/platforms/abis/llvm_abi.nim
constantine/platforms/abis/nvidia_abi.nim
constantine/platforms/llvm/llvm.nim
research/codegen/x86_instr.nim
research/codegen/x86_poc.nim
tests/gpu/hello_world_amdgpu.nim
tests/gpu/hello_world_nvidia.nim
tests/gpu/t_nvidia_fp.nim

:fire: :fire: :fire:
This adds an end-to-end LLVM IR -> AMD GPU JIT compiler.
The good news is that AMD GPUs support vectorized add-with-carry. The bad news is that unlike Nvidia GPUs, you cannot use inline assembly to guarantee it so you need to cajole the compiler into producing those:
- See details there https://github.com/mratsim/constantine/issues/92#issuecomment-2265059109
Another good news is that the device function is properly vectorized without needing to use tricks like `__forceinline__` or "Scalable Vector" types in LLVM.

AMDGPU JIT compiler

---

constantine/commitments/eth_verkle_ipa.nim
constantine/commitments/protocol_quotient_check.nim
tests/t_ethereum_verkle_ipa_primitives.nim

This is a followup to the Verkle refactoring from
- https://github.com/mratsim/constantine/pull/397
While simple proof generation / verification had an off-by-one found right away https://github.com/mratsim/constantine/pull/403,
multiproofs had:
- a multiplication missing in polynomial division that was not tested by the multiproof consistency check https://github.com/mratsim/constantine/pull/424
- a zero init missing
The current code is self-consistent, but we need more assurance that the outputs are the same as the other libraries.
Hence we keep https://github.com/mratsim/constantine/issues/396 open to make sure test coverage is improved and corner cases are hardened.

Verkle ipa multiproof is now internally consistent

---

constantine/math_compiler/codegen_amdgpu.nim
constantine/math_compiler/codegen_nvidia.nim
constantine/math_compiler/impl_fields_dispatch.nim
constantine/math_compiler/impl_fields_globals.nim
constantine/math_compiler/impl_fields_nvidia.nim
constantine/math_compiler/impl_fields_sat.nim
constantine/math_compiler/ir.nim
constantine/math_compiler/pub_fields.nim
constantine/platforms/llvm/asm_nvidia.nim
tests/gpu/hello_world_nvidia.nim
tests/gpu/t_nvidia_fp.nim

This refactors the Nvidia backend in preparation for hardware accelerated elliptic curves and fields.
The Nvidia backend has been broken following AMDGPU and x86 experiments in:
- #453
- #456
This:
- refactors the hello_world_nvidia so that it uses only low-level cuda primitives (but it may use high-level LLVM ones)
- reimplement the add/sub/mul using the new framework which should significantly reduce boilerplate.

Nvidia remastered

---

constantine-rust/constantine-ethereum-bls-sig/tests/t_ethereum_bls_sig_vectors.rs
constantine-rust/constantine-ethereum-evm-precompiles/tests/t_ethereum_evm_precompiles.rs
constantine-rust/constantine-halo2-zal/benches/msm.rs
constantine-rust/constantine-halo2-zal/tests/t_zal_msm_accel.rs
docs/zk_accel_layer.md

Halo2curves changed best_multiexp name to msm_best: https://github.com/privacy-scaling-explorations/halo2curves/pull/169

Halo2 0.4 and Halo2curves 0.7 compat + Rust warnings fixes

---

constantine/ciphers/chacha20.nim

Failing with latest `version-2-0` branch in Nim

fix: template typechecking is more stringent

---

.github/workflows/ci.yml
README.md

This fixes #472. Github removed the apt-fast package from their Ubuntu 24.04 images in CI

CI: replace apt-fast by apt-get + Nim v2.2.x in CI as Nim v2.0.10 is broken.

---

.github/workflows/ci.yml
helpers/pararun.nim

Unfortunately Nim v2.0.x has a compiler regression that prevents compiling. It was introduced in some commit and Nim devel and Nim 2.2 branch has the subsequent commit that fixes the regression.
This PR fixes the remaining Windos issues with Nim v2.2 so it can be used in CI.

Fixes for Nim v2.2

---

.github/workflows/ci.yml
README.md

We remove explicit support for Nim 1.6.x as its EOL and Nim 2.0.x as one version to the next works or does not work.
Furthermore neither 1.6.12 or 2.0.12 can compile #485
Closes #471

CI: drop old nim compiler versions

---

benchmarks/bench_eth_eip4844_kzg.nim
constantine/math/elliptic/ec_multi_scalar_mul.nim
constantine/math/elliptic/ec_multi_scalar_mul_parallel.nim
tests/parallel/t_ec_shortw_jac_g1_msm_parallel.nim
tests/parallel/t_ec_shortw_prj_g1_msm_parallel.nim

The parallel MSM skips the top window if the number of bits is exactly divided by MSM parameter c.
This is easy to reproduce with 3 points and by removing the endomorphism acceleration (which multiply the number of points by 2x or 4x) here:
https://github.com/mratsim/constantine/blob/7c3d76d6d6e4de78f3d5a4d37fe39ed4b247c491/constantine/math/elliptic/ec_multi_scalar_mul_parallel.nim#L539-L557
This might help for #479, cc @Vindaar

fix(MSM): properly handle edge condition in parallel MSM when bits is exactly divided by c

---

benchmarks/bench_h_keccak.nim
constantine/ciphers/chacha20.nim
constantine/hashes/h_keccak.nim
constantine/hashes/h_sha256.nim
constantine/hashes/keccak/keccak_generic.nim
constantine/hashes/keccak/keccak_x86_bmi1.nim
constantine/platforms/allocs.nim
constantine/platforms/bithacks.nim
constantine/serialization/endians.nim
tests/t_hash_keccak_sha3_vs_openssl.nim

This optimizes Keccak and fixes #495:
- remove the intermediate buffer and directly use Keccak state for chunked hashing.
- introduces BMI1 optimizations on x86. AVX2 and BMI2, at least naive were worst (AVX2) or unconvincing (BMI2, no change in perf, bigger code due to 2x bigger instruction)
It also addresses #499:
- rotate left by 0 gives wrong result with Clang + optimizations
Benchmarks done with Clang on Zen5
Before
After
Small hashes like 32B, the size for Merkle Tree based keccak has been improved by 16%.
And for large input we're faster than OpenSSL! without assembly.
Rustcrypto from https://github.com/mratsim/constantine/issues/495#issuecomment-2561915443
22.8% perf advantage over the Rust implementation
vs C Keccak-tiny-unrolled from …

Keccak optimizations

---

constantine-rust/constantine-sys/build.rs

- Report `nimble` build errors
- I encountered a few build errors due to missing `llvm-as`, which was not reported on the console.
- Improve rustc-link-lib directive by letting the compiler find the correct target-specific name
- I believe this should work, will revert if CI fails
- Reduce rerun-if-changed directives to reduce unnecessary re-compilations
- Currently every single `cargo build` rebuilds constantine which takes like 15s.

Improve Rust build script

---

constantine/platforms/intrinsics/addcarry_subborrow.nim

Potentially a quick win to accelerate Constantine on Apple M1~3.
See tracking compiler inefficiencies #357 
Use addcarry builtin for Clang (GCC is incredibad) on non-x86 platforms.
To be benched with `CTT_ASM=0 CC=clang nimble bench_fp`.

refactor(add-carry): with Clang on non-x86 (for example MacOS) use builtin add-carry instead of u128

---

tests/t_hash_keccak_sha3_vs_openssl.nim

On MacOS, OpenSSL is provided by LibreSSL which doesn't provide Keccak / SHA3 yet and does not provide the EVP_Q_digest API either.
So skip it for testing.

keccak: OpenSSL skip MacOS test

---

constantine/threadpool/crossthread/tasks_flowvars.nim

While fixing #502, PR #503 introduced a regression on x86 Windows, a waiter could deadlock when trying to sleep until task completion.
The fix is ensuring a full compiler and cache/memory barrier. Tested on MacOS ARM as well to ensure #502 stays fixed.
It's unsure why the issue appears only on Windows and not on Linux and it might be due to Windows Futex `wait` signaling.

fix(threadpool regression): deadlock on Windows on fibonacci

---

constantine/math_compiler/codegen_nvidia.nim
constantine/math_compiler/impl_curves_ops_affine.nim
constantine/math_compiler/impl_curves_ops_jacobian.nim
constantine/math_compiler/impl_fields_ops.nim
constantine/math_compiler/impl_msm_nvidia.nim
constantine/math_compiler/ir.nim
constantine/math_compiler/pub_curves_jacobian.nim
constantine/math_compiler/pub_fields.nim
constantine/platforms/abis/llvm_abi.nim
tests/gpu/t_ec_sum.nim
tests/gpu/t_msm.nim

This implements the bucket method on the LLVM target. In principle it is just a direct port of the reference implementation. However, to make it look mostly identical, I added helper macros for for loops and if statements. 
In addition, due to the somewhat tricky nature of dealing with LLVM types (especially with respect to pointer types), I added `MutableValue` and `ConstantValue` helpers as well as multiple further array types to deal with the different data types part of the calculation.
While  I haven't run any benchmarks (or anything resembling a real MSM, only tested with 2 inputs), this is obviously not going to be fast given that it runs entirely in serial. 
This was a (to me at least) useful implementation to see how usable one can make the LLVM IR from Nim macros for more …

Nvidia MSM proof of concept (serial)

---

constantine.nimble
constantine/ethereum_evm_precompiles.nim
constantine/hashes.nim
constantine/hashes/h_ripemd160.nim
constantine/hashes/ripemd160/ripemd160_generic.nim
tests/openssl_wrapper.nim
tests/t_ethereum_evm_precompiles.nim
tests/t_hash_ripemd160_vs_openssl.nim

The hash function implementation right now is a direct port of the bitcoin-core implementation here:
https://github.com/bitcoin-core/gui/blob/228aba2c4d9ac0b2ca3edd3c2cdf0a92e55f669b/src/crypto/ripemd160.cpp

Add RIPEMD160 hash function and EVM precompile

---

constantine.nimble
constantine/ecdsa_secp256k1.nim
constantine/eth_ecdsa_signatures.nim
constantine/ethereum_evm_precompiles.nim
constantine/serialization/codecs_ecdsa_secp256k1.nim
constantine/signatures/ecdsa.nim
tests/ecdsa/t_ecdsa_verify_openssl.nim
tests/openssl_wrapper.nim
tests/t_ethereum_evm_precompiles.nim

This builds on top of the ECDSA implementation in PR #490 and adds public key recovery. Based on that implementing the `ECRecover` precompile is quite straightforward (recover an Ethereum address based on a given message digest and signature). 
We base our implementation of the precompile on Geth's implementation here:
https://github.com/ethereum/go-ethereum/blob/341647f1865dab437a690dc1424ba71495de2dd8/core/vm/contracts.go#L243-L272
and to a lesser extent appendix F in the Ethereum Yellow Paper.
For the general ECDSA public key recovery API I went with a variable time implementation. To my understanding this is essentially needed regardless, due to the fact that the signing process converts the coordinate of the point `R` in `Fp` to a scalar in `Fr`. While unlikely for Secp256k1 (because …

Add `ECRecover` EVM precompile

---

constantine/math/arithmetic/finite_fields.nim

Both branches of a `when nimvm` statement are compiled, so this import is always processed.

remove `when nimvm` condition to import

---

constantine/math/arithmetic/bigints.nim
constantine/math/arithmetic/limbs.nim
constantine/named/deriv/precompute.nim

This clarifies the precondition for shiftRight, i.e. a non-zero, non-max to avoid all exceptional/ISA-defined path.
shiftRight was initially introduced to optimized GCD/modular inversion in https://github.com/mratsim/constantine/commit/bde619155b34182552a236652842e9be12b863e5.
Today it is used in a couple more places and there are no "zero" input expected in constant-time path. In fact all inputs are statically known, the proc doesn't use a static k to avoid code bloat / monomorphization.
A version that can handles zero and sizes over the word bitwidth is available as `shiftRight_vartime`.

docs: Update documentation of shiftRight, fixes #537

---

constantine.nimble

This only happens if the static library wasn't built before.
Due to the ordering in `make_lib` and `make_lib_rust` in CI, I assume the actual building of the lib was skipped.

fix(cargo): missing space when compiling Rust on MacOS for --passC:-fPIC

---

constantine/math_compiler/experimental/cuda_execute_dsl.nim
constantine/math_compiler/experimental/nim_ast_to_cuda_ast.nim
constantine/math_compiler/experimental/nvrtc_field_ops.nim
constantine/math_compiler/experimental/runtime_compile.nim
constantine/platforms/abis/nvidia_abi.nim
tests/gpu/t_nvrtc_misc_ops.nim

Our previous approach of just a bare `distinct pointer` now leads to a mismatched pointer error on modern GCC / Clang.
Similarly for `cuGetErrorString` we now *need* a `const char**` argument and not just a `char **` argument...
Edit:
And a couple of other things I just noticed running some of the NVRTC tests locally:
- I hadn't ever committed the correct `slct` proc syntax (takes `int32` instead of `uint32`)
- fix a regression where we would generate duplicate device pointers if one passes in the same argument as an input twice
- avoids the need to hardcode the limb size in `defCoreFieldOps` 
Note: I still see test failures here that elude me at the moment. I'll need some time to debug them. Still, at least the code compiles and runs again, heh.

fix NVRTC CUDA backend due to incompatible pointer types

---

tests/gpu/t_nvidia_fp.nim
tests/math_fields/t_finite_fields_mulsquare.nim

Following #445, there are 2 representations used on CPU for field elements, either the canonical representation if a field has access to a fast reduction like for Mersenne or Pseudo-Mersenne/Crandall or Solinas primes or the Montgomery representation.
The Nvidia backend only supports Montgomery representation at the moment.
Inputs are memcpied into the GPU for computation assuming CPU and GPU representations are matching but they aren't.
Workarounding by checking if the inputs and output should be memcpied or not seems to be non-trivial work so for now we don't support Edwards25519 on Nvidia GPU while waiting got the Crandall acceleration introduced in #445, namely this file https://github.com/mratsim/constantine/blob/v0.2.0/constantine/math/arithmetic/limbs_crandall.nim to be ported to …

Nvidia: deactivate Edwards25519 on Nvidia backend for now
